/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-08-06 13:30:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

public final class admindoctoredit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/component/db.jsp", Long.valueOf(1659757894513L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"component/error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

Class.forName("com.mysql.jdbc.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hos","root","sparsh1574");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write(".contain{\r\n");
      out.write("            margin: 5vh auto;\r\n");
      out.write("            width:80%;\r\n");
      out.write("            background: rgb(15, 15, 15);\r\n");
      out.write("            width: 350px;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 2em;\r\n");
      out.write("        }\r\n");
      out.write("        .head{\r\n");
      out.write("            font-size: 2em;\r\n");
      out.write("            margin-bottom: 0.5em;\r\n");
      out.write("        }\r\n");
      out.write("        .bo {\r\n");
      out.write("            margin: 0.2em 0;\r\n");
      out.write("        }\r\n");
      out.write("        .contain .bo p{\r\n");
      out.write("            color: rgba(255, 255, 255, 0.781);\r\n");
      out.write("        }\r\n");
      out.write("        .contain .bo div{\r\n");
      out.write("            position: relative;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            margin: 0.5em 0;\r\n");
      out.write("        }\r\n");
      out.write("        .contain .bo input{\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background: rgb(255, 255, 255);\r\n");
      out.write("            color: rgb(0, 0, 0);\r\n");
      out.write("            border: none;\r\n");
      out.write("            outline: none;\r\n");
      out.write("            padding-left: 0.8em;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            transition: all .4s\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .contain .bo input:focus::placeholder{\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        .contain .bo div::before{\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 50%;\r\n");
      out.write("            left: 50%;\r\n");
      out.write("            transform: translate(-50%, -50%);\r\n");
      out.write("            width: 102%;\r\n");
      out.write("            height: 105%;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            background: linear-gradient(to right, #ff416c, #ff4b2b);\r\n");
      out.write("        }\r\n");
      out.write("        .loginBtn{\r\n");
      out.write("            width: 102%;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            margin: 0.5em 0;\r\n");
      out.write("            transform: translate(-1%);\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            color: white;\r\n");
      out.write("            background: linear-gradient(to right, #ff416c, #ff4b2b);\r\n");
      out.write("            transition: all .4s;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .loginBtn:hover{\r\n");
      out.write("            transform: translate(-1%, 5%);\r\n");
      out.write("            box-shadow: 0 0 10px #ff416d65;\r\n");
      out.write("        }\r\n");
      out.write("        .text{\r\n");
      out.write("            font-size: 0.8em;\r\n");
      out.write("            margin-top: 0.5em;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: rgba(255, 255, 255, 0.623);\r\n");
      out.write("        }\r\n");
      out.write("        .text a{\r\n");
      out.write("            color: rgba(255, 255, 255, 0.911);\r\n");
      out.write("        }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

String id1 = request.getParameter("id1");
String qr = "select * from doctor where id=?";
PreparedStatement st = con.prepareStatement(qr);
st.setString(1, id1);
ResultSet rs = st.executeQuery();
if(rs.next())
{
	    String name = rs.getString("name");
		String dob = rs.getString("dob");
		String qualification = rs.getString("qualification");
		String specialist = rs.getString("specialist");
		String email = rs.getString("email");
		String mobile = rs.getString("mobile");
		
      out.write(" \r\n");
      out.write("		<div class=\"contain\">\r\n");
      out.write("        <p class=\"head\">Update Doctor Details</p>\r\n");
      out.write("        <form action=\"UpdateDoctor?id1=");
      out.print(id1 );
      out.write("\" method=\"post\">\r\n");
      out.write("        <div class=\"bo\">\r\n");
      out.write("            <p>Name</p>\r\n");
      out.write("            <div>\r\n");
      out.write("                <input type=\"text\" name=\"name\" value=\"");
      out.print( name);
      out.write("\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"bo\">\r\n");
      out.write("            <p>Date Of Birth</p>\r\n");
      out.write("            <div>\r\n");
      out.write("                <input type=\"text\" name=\"dob\" value=\"");
      out.print( dob);
      out.write("\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"bo\">\r\n");
      out.write("            <p>Qualification</p>\r\n");
      out.write("            <div>\r\n");
      out.write("                <input type=\"text\" name=\"qualification\" value=\"");
      out.print( qualification);
      out.write("\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"bo\">\r\n");
      out.write("            <p>Specialization</p>\r\n");
      out.write("            <div>\r\n");
      out.write("                <input type=\"text\" name=\"specialist\" value=\"");
      out.print( specialist);
      out.write("\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"bo\">\r\n");
      out.write("            <p>Email</p>\r\n");
      out.write("            <div>\r\n");
      out.write("                <input type=\"email\" name=\"email\" value=\"");
      out.print( email);
      out.write("\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"bo\">\r\n");
      out.write("            <p>Mobile</p>\r\n");
      out.write("            <div>\r\n");
      out.write("                <input type=\"text\" name=\"mobile\" value=\"");
      out.print( mobile);
      out.write("\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <button type=\"submit\"  class=\"loginBtn\">Update Doctor Details</button> \r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("		");

}
else
{
	out.println("no record found");
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
