/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-08-20 05:30:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/component/allcss.jsp", Long.valueOf(1659750950803L));
    _jspx_dependants.put("/component/navbar.jsp", Long.valueOf(1660973304075L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css\" integrity=\"sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- <nav class=\"navbar navbar-expand-lg navbar-dark bg-success\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"index.jsp\"><i class=\"fas fa-clinic-medical\"></i> Medi Home</a>\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("      <ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link active\" aria-current=\"page\" href=\"admin_login.jsp\"><i class=\"fas fa-sign-in-alt\"></i> ADMIN</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link active\" aria-current=\"page\" href=\"doctor_login.jsp\">DOCTOR</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link active\" aria-current=\"page\" href=\"#\">APPOINMENT</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link active\" aria-current=\"page\" href=\"user_login.jsp\">USER</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item dropdown\">\r\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("            Dropdown\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Action</a></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>\r\n");
      out.write("            <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav> -->\r\n");
      out.write("<style>\n");
      out.write("<!--\n");
      out.write(".header{\r\n");
      out.write("    \r\n");
      out.write("    width: 100%;\r\n");
      out.write("    background-image: url(\"img/banner.jpg\");\r\n");
      out.write("    background-position: center;\r\n");
      out.write("    background-repeat: no-repeat;\r\n");
      out.write("    background-size: cover;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("nav{\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    background-color: #222831;\r\n");
      out.write("}\r\n");
      out.write(".logo{\r\n");
      out.write("    margin: 20px;\r\n");
      out.write("}\r\n");
      out.write(".logo a:hover{\r\n");
      out.write("    font-size: 40px;\r\n");
      out.write("}\r\n");
      out.write(".logo a{\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-size: 30px;\r\n");
      out.write("    color: white;\r\n");
      out.write("}\r\n");
      out.write(".logo span{\r\n");
      out.write("    color: rgb(251, 8, 8);\r\n");
      out.write("    font-size: 30px;\r\n");
      out.write("}\r\n");
      out.write(".nav-links{\r\n");
      out.write("   text-align: right;\r\n");
      out.write("}\r\n");
      out.write(".nav-links ul{\r\n");
      out.write("    display: flex;\r\n");
      out.write("    margin: 20px;\r\n");
      out.write("}\r\n");
      out.write(".nav-links ul li{\r\n");
      out.write("    display: flex;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    padding: 8px 12px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write(".nav-links ul li a{\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-links ul li a:hover{\r\n");
      out.write("    background-color: gray;\r\n");
      out.write("    color: black;\r\n");
      out.write("    padding: 15px;\r\n");
      out.write("    border: 3px solid black;\r\n");
      out.write("    border-radius: 12px;\r\n");
      out.write("    margin: 3px;\r\n");
      out.write("}\r\n");
      out.write("nav .fa{\r\n");
      out.write("    display: none;\r\n");
      out.write("}\r\n");
      out.write("@media(max-width: 700px){\r\n");
      out.write("    \r\n");
      out.write("    .nav-links ul {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("     }\r\n");
      out.write("     .nav-links ul li{\r\n");
      out.write("        margin-bottom: 25%;\r\n");
      out.write("        margin-top: 25%;\r\n");
      out.write("     }\r\n");
      out.write("    .nav-links ul li a{\r\n");
      out.write("        color: black;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("     }\r\n");
      out.write("    \r\n");
      out.write("     \r\n");
      out.write("     .nav-links{\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        right: -200px;\r\n");
      out.write("        background-color: orange;\r\n");
      out.write("        height: 100vh;\r\n");
      out.write("        width: 200px;\r\n");
      out.write("        z-index: 1;\r\n");
      out.write("        text-align: left;\r\n");
      out.write("     }\r\n");
      out.write("     nav .fa{\r\n");
      out.write("         display: block;\r\n");
      out.write("         color: #fff;\r\n");
      out.write("         margin: 10px;\r\n");
      out.write("         font-size: 22px;\r\n");
      out.write("     }\r\n");
      out.write("     .nav-links ul{\r\n");
      out.write("         padding: 30px;\r\n");
      out.write("         transition-delay: 2s;\r\n");
      out.write("     }\r\n");
      out.write("}\r\n");
      out.write("/* .text-area{\r\n");
      out.write("    border: 2px solid green;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    margin: auto;\r\n");
      out.write("    top: 20vh;\r\n");
      out.write("    width: 90%;\r\n");
      out.write("}\r\n");
      out.write(".text-area h3{\r\n");
      out.write("    color: rgb(87, 21, 21);\r\n");
      out.write("    font-size: 28px;\r\n");
      out.write("}\r\n");
      out.write(".text-area h1{\r\n");
      out.write("    font-size: 35px;\r\n");
      out.write("} */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".h1_tag{\r\n");
      out.write("    \r\n");
      out.write("        font-size: 36px;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write(".h3_tag{\r\n");
      out.write("    \r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        color: crimson;\r\n");
      out.write("    }\n");
      out.write("-->\n");
      out.write("</style>\r\n");
      out.write("<section class=\"header\" id=\"header\">\r\n");
      out.write("      <nav>\r\n");
      out.write("        <div class=\"logo\" ><a href=\"index.html\"><i class=\"fas fa-clinic-medical\"></i> Medi<span>Home</span></a></div>\r\n");
      out.write("        <div class=\"nav-links\" id=\"navLinks\">\r\n");
      out.write("            <i class=\"fa fa-window-close\" aria-hidden=\"true\" onclick=\"hideMenu()\"></i>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"index.jsp\">HOME</a></li>\r\n");
      out.write("                <li><a href=\"admin_login.jsp\">ADMIN</a></li>\r\n");
      out.write("                <li><a href=\"doctor_login.jsp\">DOCTOR</a></li>\r\n");
      out.write("                <li><a href=\"user_login.jsp\">USER</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <i class=\"fa fa-bars\" aria-hidden=\"true\" onclick=\"showMenu()\"></i>\r\n");
      out.write("      </nav>\r\n");
      out.write("      <!-- <div class=\"text-area\">\r\n");
      out.write("        <h3>Hello, my name is</h3>\r\n");
      out.write("        <h1>Sparsh Garg</h1>\r\n");
      out.write("        <h3>and I'm a Developer</h3>\r\n");
      out.write("      </div> -->\r\n");
      out.write("    </section>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"carouselExampleIndicators\" class=\"carousel slide\" data-bs-ride=\"carousel\">\r\n");
      out.write("  <div class=\"carousel-indicators\">\r\n");
      out.write("    <button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"0\" class=\"active\" aria-current=\"true\" aria-label=\"Slide 1\"></button>\r\n");
      out.write("    <button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"1\" aria-label=\"Slide 2\"></button>\r\n");
      out.write("    <button type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide-to=\"2\" aria-label=\"Slide 3\"></button>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"carousel-inner\">\r\n");
      out.write("    <div class=\"carousel-item active\">\r\n");
      out.write("      <img src=\"img/hos1.jpg\" class=\"d-block w-100\" alt=\"...\" height=\"500px\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"carousel-item\">\r\n");
      out.write("      <img src=\"img/hos2.jpg\" class=\"d-block w-100\" alt=\"...\" height=\"500px\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"carousel-item\">\r\n");
      out.write("      <img src=\"img/hos3.jpg\" class=\"d-block w-100\" alt=\"...\" height=\"500px\">\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide=\"prev\">\r\n");
      out.write("    <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("    <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("  </button>\r\n");
      out.write("  <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselExampleIndicators\" data-bs-slide=\"next\">\r\n");
      out.write("    <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("    <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("  </button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container p-3\">\r\n");
      out.write("<h1 class=\"text-center fs-2\">Key Feature Of Hospital</h1>\r\n");
      out.write("<div class=\"card-columns\">\r\n");
      out.write("  <div class=\"card bg-primary p-2 m-2 border-dark shadow rounded\">\r\n");
      out.write("    <div class=\"card-body text-center\">\r\n");
      out.write("      <p class=\"card-text font-weight-bold\">100% Safety</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"card bg-secondary p-2 m-2 border-dark shadow rounded\">\r\n");
      out.write("    <div class=\"card-body text-center\">\r\n");
      out.write("      <p class=\"card-text font-weight-bold\">Friendly Doctors</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"card bg-success p-2 m-2 border-dark shadow rounded\">\r\n");
      out.write("    <div class=\"card-body text-center\">\r\n");
      out.write("      <p class=\"card-text\">Clean Environment</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"card bg-danger p-2 m-2 border-dark shadow rounded\">\r\n");
      out.write("    <div class=\"card-body text-center\">\r\n");
      out.write("      <p class=\"card-text font-weight-bold\">Medical Research</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"card bg-warning p-2 m-2 border-dark shadow rounded\">\r\n");
      out.write("    <div class=\"card-body text-center\">\r\n");
      out.write("      <p class=\"card-text font-weight-bold\">Personalized and specialized  Care for patients</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"card bg-info p-2 m-2 border-dark shadow rounded\">\r\n");
      out.write("    <div class=\"card-body text-center\">\r\n");
      out.write("      <p class=\"card-text font-weight-bold\">Ultra modern technologies</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container p-3\">\r\n");
      out.write("<h1 class=\"text-center fs-2\">Our Teams</p>\r\n");
      out.write("<div class=\"py-5 text-center text-info background-info\" style=\"\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"col-lg-4 col-md-6 p-4\"> <img class=\"img-fluid d-block mb-3 mx-auto rounded-circle\" alt=\"Card image cap\" width=\"200\" src=\"img/doc-1.jpg\">\r\n");
      out.write("<h4 class=\"text-dark\">Dr. John kandy</h4>\r\n");
      out.write("<h4 class=\"mb-0 text-secondary\">Cardiologist</h4>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-lg-4 col-md-6 p-4\"> <img class=\"img-fluid d-block mb-3 mx-auto rounded-circle\" src=\"img/doc-2.jpg\" alt=\"Card image cap\" width=\"200\">\r\n");
      out.write("<h4 class=\"text-dark\">Dr. Sam ilana</h4>\r\n");
      out.write("<h4 class=\"mb-0 text-secondary\">General surgeon</h4>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-lg-4 p-4\"> <img class=\"img-fluid d-block mb-3 mx-auto rounded-circle\" src=\"img/doc-3.jpg\" width=\"200\">\r\n");
      out.write("<h4 class=\"text-dark\">Dr. Maria Samantha</h4>\r\n");
      out.write("<h4 class=\"mb-0 text-secondary\">Neurosurgeon</h4>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div> \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer class=\"bg-dark text-center text-white\">\r\n");
      out.write("  <!-- Grid container -->\r\n");
      out.write("  <div class=\"container p-4\">\r\n");
      out.write("    <!-- Section: Social media -->\r\n");
      out.write("    <section class=\"mb-4\">\r\n");
      out.write("      <!-- Facebook -->\r\n");
      out.write("      <a class=\"btn btn-outline-light btn-floating m-1\" href=\"#!\" role=\"button\"\r\n");
      out.write("        ><i class=\"fab fa-facebook-f\"></i\r\n");
      out.write("      ></a>\r\n");
      out.write("\r\n");
      out.write("      <!-- Twitter -->\r\n");
      out.write("      <a class=\"btn btn-outline-light btn-floating m-1\" href=\"#!\" role=\"button\"\r\n");
      out.write("        ><i class=\"fab fa-twitter\"></i\r\n");
      out.write("      ></a>\r\n");
      out.write("\r\n");
      out.write("      <!-- Google -->\r\n");
      out.write("      <a class=\"btn btn-outline-light btn-floating m-1\" href=\"#!\" role=\"button\"\r\n");
      out.write("        ><i class=\"fab fa-google\"></i\r\n");
      out.write("      ></a>\r\n");
      out.write("\r\n");
      out.write("      <!-- Instagram -->\r\n");
      out.write("      <a class=\"btn btn-outline-light btn-floating m-1\" href=\"#!\" role=\"button\"\r\n");
      out.write("        ><i class=\"fab fa-instagram\"></i\r\n");
      out.write("      ></a>\r\n");
      out.write("\r\n");
      out.write("      <!-- Linkedin -->\r\n");
      out.write("      <a class=\"btn btn-outline-light btn-floating m-1\" href=\"#!\" role=\"button\"\r\n");
      out.write("        ><i class=\"fab fa-linkedin-in\"></i\r\n");
      out.write("      ></a>\r\n");
      out.write("\r\n");
      out.write("      <!-- Github -->\r\n");
      out.write("      <a class=\"btn btn-outline-light btn-floating m-1\" href=\"#!\" role=\"button\"\r\n");
      out.write("        ><i class=\"fab fa-github\"></i\r\n");
      out.write("      ></a>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Section: Social media -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Section: Form -->\r\n");
      out.write("    <section class=\"\">\r\n");
      out.write("      <form action=\"\">\r\n");
      out.write("        <!--Grid row-->\r\n");
      out.write("        <div class=\"row d-flex justify-content-center\">\r\n");
      out.write("          <!--Grid column-->\r\n");
      out.write("          <div class=\"col-auto\">\r\n");
      out.write("            <p class=\"pt-2\">\r\n");
      out.write("              <strong>Sign up for our newsletter</strong>\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!--Grid column-->\r\n");
      out.write("\r\n");
      out.write("          <!--Grid column-->\r\n");
      out.write("          <div class=\"col-md-5 col-12\">\r\n");
      out.write("            <!-- Email input -->\r\n");
      out.write("            <div class=\"form-outline form-white mb-4\">\r\n");
      out.write("              <input type=\"email\" id=\"form5Example21\" class=\"form-control\" />\r\n");
      out.write("              <label class=\"form-label\" for=\"form5Example21\">Email address</label>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!--Grid column-->\r\n");
      out.write("\r\n");
      out.write("          <!--Grid column-->\r\n");
      out.write("          <div class=\"col-auto\">\r\n");
      out.write("            <!-- Submit button -->\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-outline-light mb-4\">\r\n");
      out.write("              Subscribe\r\n");
      out.write("            </button>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!--Grid column-->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--Grid row-->\r\n");
      out.write("      </form>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Section: Form -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Section: Text -->\r\n");
      out.write("    <section class=\"mb-4\">\r\n");
      out.write("      <p>\r\n");
      out.write("        Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt distinctio earum\r\n");
      out.write("        repellat quaerat voluptatibus placeat nam, commodi optio pariatur est quia magnam\r\n");
      out.write("        eum harum corrupti dicta, aliquam sequi voluptate quas.\r\n");
      out.write("      </p>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Section: Text -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Section: Links -->\r\n");
      out.write("   <!--  <section class=\"\">\r\n");
      out.write("      Grid row\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        Grid column\r\n");
      out.write("        <div class=\"col-lg-3 col-md-6 mb-4 mb-md-0\">\r\n");
      out.write("          <h5 class=\"text-uppercase\">Links</h5>\r\n");
      out.write("\r\n");
      out.write("          <ul class=\"list-unstyled mb-0\">\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"#!\" class=\"text-white\">Home</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"#!\" class=\"text-white\">Admin</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"#!\" class=\"text-white\">Doctor</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("              <a href=\"#!\" class=\"text-white\">User</a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      Grid row\r\n");
      out.write("    </section> -->\r\n");
      out.write("    <!-- Section: Links -->\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- Grid container -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Copyright -->\r\n");
      out.write("  <div class=\"text-center p-3\" style=\"background-color: rgba(0, 0, 0, 0.2);\">\r\n");
      out.write("    © 2020 Copyright:\r\n");
      out.write("    <a class=\"text-white\" href=\"index.jsp\">MediHome</a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- Copyright -->\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
